// <auto-generated />
using System;
using CafeLab.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeLab.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CafeLab.API.CostosLote.Domain.Model.CostoLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ManoObra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MateriaPrima")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OtrosCostos")
                        .HasColumnType("int");

                    b.Property<int>("Procesamiento")
                        .HasColumnType("int");

                    b.Property<string>("Transporte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CostosLote");
                });

            modelBuilder.Entity("CafeLab.API.CuppingSessions.Domain.Model.CuppingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CuppingSessions");
                });

            modelBuilder.Entity("CafeLab.API.MovimientosInventario.Domain.Model.MovimientoInventario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cantidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoCafe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("CafeLab.API.CostosLote.Domain.Model.CostoLote", b =>
                {
                    b.OwnsOne("CafeLab.API.CostosLote.Domain.Model.Detalle", "Detalle", b1 =>
                        {
                            b1.Property<int>("CostoLoteId")
                                .HasColumnType("int");

                            b1.Property<int>("AguaUtilizada")
                                .HasColumnType("int");

                            b1.Property<double>("CantidadCafeVerde")
                                .HasColumnType("double");

                            b1.Property<int>("CantidadTransporteCafeVerde")
                                .HasColumnType("int");

                            b1.Property<int>("Certificaciones")
                                .HasColumnType("int");

                            b1.Property<int>("ControlCalidad")
                                .HasColumnType("int");

                            b1.Property<int>("CostoDiarioAlmacen")
                                .HasColumnType("int");

                            b1.Property<double>("CostoKgCafeVerde")
                                .HasColumnType("double");

                            b1.Property<double>("CostoPorHora")
                                .HasColumnType("double");

                            b1.Property<double>("CostoTransporteKgCafeVerde")
                                .HasColumnType("double");

                            b1.Property<int>("DepreciacionEquipos")
                                .HasColumnType("int");

                            b1.Property<int>("DiasAlmacen")
                                .HasColumnType("int");

                            b1.Property<int>("EnergiaElectrica")
                                .HasColumnType("int");

                            b1.Property<int>("GastosAdministrativos")
                                .HasColumnType("int");

                            b1.Property<int>("HorasTrabajadas")
                                .HasColumnType("int");

                            b1.Property<int>("InsumosProcesamiento")
                                .HasColumnType("int");

                            b1.Property<int>("MantenimientoMaquinaria")
                                .HasColumnType("int");

                            b1.Property<int>("NumeroTrabajadores")
                                .HasColumnType("int");

                            b1.Property<int>("Seguros")
                                .HasColumnType("int");

                            b1.HasKey("CostoLoteId");

                            b1.ToTable("CostosLote");

                            b1.WithOwner()
                                .HasForeignKey("CostoLoteId");
                        });

                    b.OwnsOne("CafeLab.API.CostosLote.Domain.Model.Totales", "Totales", b1 =>
                        {
                            b1.Property<int>("CostoLoteId")
                                .HasColumnType("int");

                            b1.Property<double>("CostPerCup")
                                .HasColumnType("double");

                            b1.Property<double>("CostPerKg")
                                .HasColumnType("double");

                            b1.Property<double>("TotalLote")
                                .HasColumnType("double");

                            b1.HasKey("CostoLoteId");

                            b1.ToTable("CostosLote");

                            b1.WithOwner()
                                .HasForeignKey("CostoLoteId");
                        });

                    b.Navigation("Detalle")
                        .IsRequired();

                    b.Navigation("Totales")
                        .IsRequired();
                });

            modelBuilder.Entity("CafeLab.API.CuppingSessions.Domain.Model.CuppingSession", b =>
                {
                    b.OwnsOne("CafeLab.API.CuppingSessions.Domain.Model.Ratings", "Ratings", b1 =>
                        {
                            b1.Property<int>("CuppingSessionId")
                                .HasColumnType("int");

                            b1.Property<int>("Acidez")
                                .HasColumnType("int");

                            b1.Property<int>("Balance")
                                .HasColumnType("int");

                            b1.Property<int>("Cuerpo")
                                .HasColumnType("int");

                            b1.Property<int>("Fragancia")
                                .HasColumnType("int");

                            b1.Property<int>("Postgusto")
                                .HasColumnType("int");

                            b1.Property<int>("Sabor")
                                .HasColumnType("int");

                            b1.HasKey("CuppingSessionId");

                            b1.ToTable("CuppingSessions");

                            b1.WithOwner()
                                .HasForeignKey("CuppingSessionId");
                        });

                    b.Navigation("Ratings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
